name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install needed software
      run: gem install xcpretty
    - name: Run tests
      run: xcodebuild test -workspace SwiftPascalInterpreter.xcworkspace -scheme PascalInterpreter -destination 'platform=OS X,arch=x86_64' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty